### ISSUE TITLE
Commented lines in nitro.yaml are deleted

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/nitro#395] opened 2021-08-13 10:52 UTC
### Description

I only added comments as a way to try and mitigate Nitro spinning up all containers whenever you do anything with it, but... I was not expecting all of my commented out config to be deleted by Nitro. That's a bit of a pain.

Is it possible to stop Nitro from deleting comments in the config file?

### Steps to reproduce

1. Comment out one of the container configs, or just add a comment in the yaml file
2. Do a nitro apply or nitro restart etc
3. See that the comments are gone

### Additional info

- Nitro version: 2.0.8

**Comment by angrybrad** [comment] 2021-08-13 18:34
Closing this as a dupe of https://github.com/craftcms/nitro/issues/335

**Comment by angrybrad** [comment] 2021-08-13 18:53
Sorry... just saw the conversation around this in Discord.

**Comment by jasonmccallister** [comment] 2022-07-06 15:34
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.

**Closed by jasonmccallister** 2022-07-06 15:34 UTC
Labels: bug
