### ISSUE TITLE
`nitro extensions` wonky behavior

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#339] opened 2021-04-20 22:59 UTC
### Description

After some random sampling, it seems that _none_ of the extensions the command accepts get enabled for php-fpm and _some_ of the extensions get enabled for the cli.

For example, nitro.yaml

```
sites:
    - hostname: craft3.support.test
      path: ~/dev/support/craft3.support.test
      version: "7.4"
      extensions:
        - pcntl
        - xsl
```

Utilities->PHP Info from the Craft control panel doesn't list either (other than unrelated author credits).

If you `nitro ssh` into the site, you get nothing for `xsl`:

```
~/dev/support/craft3.support.test 3m 9s
❯ nitro ssh
connecting to craft3.support.test
/app $ php -i | grep "xsl"
/app $
```

But you do get results for `pcntl`:

```
/app $ php -i | grep "pcntl"
/usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini,
pcntl
pcntl support => enabled
```

And if you remove all of the extensions from nitro.yaml, run `nitro apply`, then `nitro ssh`, `pcntl` is now missing from the CLI (as expected):

```
❯ nitro ssh
connecting to craft3.support.test
/app $ php -i | grep "pcntl"
/app $
```

### Additional info

- Nitro version: 2.0.7
- Docker version: 3.3.1

**Comment by Sietsche** [comment] 2022-01-06 08:18
I can confirm this issue is still present. Seems to be related to enabling the xsl PHP extension. Other extensions do seem to propagate okay. Couldn't figure out a fix.

**Comment by lenvanessen** [comment] 2022-01-06 08:21
Also an issue for the firebird extension

**Comment by jasonmccallister** [comment] 2022-07-06 15:30
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.

**Closed by jasonmccallister** 2022-07-06 15:30 UTC
Labels: bug
