### ISSUE TITLE
[2.0.0-beta.7] After restarting computer all Nitro sites return 503 - error in console - The Nitro CLI and gRPC versions do not match

### ISSUE THREAD

**Issue by toddpadwick** [craftcms/nitro#261] opened 2021-03-01 08:48 UTC
### Description
I had nitro running fine last week (apart from a slight issue with case sensitive paths mentioned in [this ticket](https://github.com/craftcms/nitro/issues/249) which I fixed by manually updating the paths in `nitro edit`. But since the weekend (and probably a few computer restarts) I can no longer run any Nitro sites. When running `Nitro apply` and `nitro restart`, Nitro appears to run as normal in the console – but I just can't access any websites in the browser.

I could really do with a fix pretty rapidly, as I have a few deadlines today - I would downgrade back to version 1 but I had issues with multipass in version 1, where it regularly returned `error: exit status 2` and so became unusable :(

When running `nitro version` I see this error, but not sure if this is relevant - `The Nitro CLI and gRPC versions do not match`

### Steps to reproduce

1. Install Nitro and add site
2. Use Nitro as normal
3. Restart computer
4. Try accessing the sites using the same hostnames - they now return 503

### Additional info

When running `nitro edit`

```
databases:
    - engine: mysql
      version: "8.0"
      port: "3307"
services:
    dynamodb: false
    mailhog: false
    minio: false
    redis: true
sites:
    - hostname: madefair-api
      path: /Users/toddpadwick/Sites/madefair-api
      version: "7.4"
      webroot: web
      xdebug: false
      blackfire: false
    - hostname: thewriter
      path: /Users/toddpadwick/Sites/thewriter
      version: "7.4"
      webroot: web
      xdebug: false
      blackfire: false
    - hostname: riskybydesign
      path: /Users/toddpadwick/Sites/riskybydesign
      version: "7.4"
      webroot: web
      xdebug: false
      blackfire: false
```

When running `nitro version`

```
View the changelog at https://github.com/craftcms/nitro/blob/2.0.0-beta.7/CHANGELOG.md

Nitro CLI: 	 2.0.0-beta.7
Nitro gRPC: 	 
Docker API: 	 1.41 (1.12 min)
Docker CLI: 	 1.41

The Nitro CLI and gRPC versions do not match
You might need to run `nitro update`
```

When running `nitro logs`
```
2021-03-01 08:21:53,547 INFO supervisord started with pid 1
2021-03-01 08:21:54,553 INFO spawned: 'nginx' with pid 8
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2021-03-01 08:21:54,555 INFO spawned: 'php-fpm' with pid 9
[01-Mar-2021 08:21:54] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[01-Mar-2021 08:21:54] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[01-Mar-2021 08:21:54] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[01-Mar-2021 08:21:54] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[01-Mar-2021 08:21:54] NOTICE: fpm is running, pid 9
[01-Mar-2021 08:21:54] NOTICE: ready to handle connections
2021-03-01 08:21:55,594 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-01 08:21:55,595 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-01 08:22:53,677 WARN received SIGTERM indicating exit request
[01-Mar-2021 08:22:53] NOTICE: Terminating ...
2021-03-01 08:22:53,677 INFO waiting for nginx, php-fpm to die
[01-Mar-2021 08:22:53] NOTICE: exiting, bye-bye!
2021-03-01 08:22:53,722 INFO stopped: php-fpm (exit status 0)
2021/03/01 08:22:53 [alert] 8#8: unlink() "/run/nginx.pid" failed (13: Permission denied)
2021-03-01 08:22:53,767 WARN received SIGQUIT indicating exit request
2021-03-01 08:22:53,768 INFO stopped: nginx (exit status 0)
2021-03-01 08:29:13,505 INFO supervisord started with pid 1
2021-03-01 08:29:14,508 INFO spawned: 'nginx' with pid 8
2021-03-01 08:29:14,509 INFO spawned: 'php-fpm' with pid 9
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
[01-Mar-2021 08:29:14] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[01-Mar-2021 08:29:14] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[01-Mar-2021 08:29:14] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[01-Mar-2021 08:29:14] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[01-Mar-2021 08:29:14] NOTICE: fpm is running, pid 9
[01-Mar-2021 08:29:14] NOTICE: ready to handle connections
2021-03-01 08:29:15,721 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-01 08:29:15,725 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-01 08:31:07,041 WARN received SIGQUIT indicating exit request
2021-03-01 08:31:07,049 INFO waiting for nginx, php-fpm to die
[01-Mar-2021 08:31:07] NOTICE: Terminating ...
[01-Mar-2021 08:31:07] NOTICE: exiting, bye-bye!
2021-03-01 08:31:07,058 INFO stopped: php-fpm (exit status 0)
2021/03/01 08:31:07 [alert] 8#8: unlink() "/run/nginx.pid" failed (13: Permission denied)
2021-03-01 08:31:07,103 INFO stopped: nginx (exit status 0)
2021-03-01 08:31:15,054 INFO supervisord started with pid 1
2021-03-01 08:31:16,056 INFO spawned: 'nginx' with pid 9
2021-03-01 08:31:16,057 INFO spawned: 'php-fpm' with pid 10
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
[01-Mar-2021 08:31:16] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[01-Mar-2021 08:31:16] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[01-Mar-2021 08:31:16] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[01-Mar-2021 08:31:16] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[01-Mar-2021 08:31:16] NOTICE: fpm is running, pid 10
[01-Mar-2021 08:31:16] NOTICE: ready to handle connections
2021-03-01 08:31:17,118 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-01 08:31:17,121 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-01 08:36:28,733 WARN received SIGQUIT indicating exit request
2021-03-01 08:36:28,737 INFO waiting for nginx, php-fpm to die
[01-Mar-2021 08:36:28] NOTICE: Terminating ...
[01-Mar-2021 08:36:28] NOTICE: exiting, bye-bye!
2021-03-01 08:36:28,763 INFO stopped: php-fpm (exit status 0)
2021/03/01 08:36:28 [alert] 9#9: unlink() "/run/nginx.pid" failed (13: Permission denied)
2021-03-01 08:36:28,793 INFO stopped: nginx (exit status 0)
2021-03-01 08:36:29,549 INFO supervisord started with pid 1
2021-03-01 08:36:30,551 INFO spawned: 'nginx' with pid 9
2021-03-01 08:36:30,553 INFO spawned: 'php-fpm' with pid 10
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
[01-Mar-2021 08:36:30] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[01-Mar-2021 08:36:30] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[01-Mar-2021 08:36:30] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[01-Mar-2021 08:36:30] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[01-Mar-2021 08:36:30] NOTICE: fpm is running, pid 10
[01-Mar-2021 08:36:30] NOTICE: ready to handle connections
2021-03-01 08:36:31,608 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-01 08:36:31,608 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

```

- Nitro version: 2.0.0-beta.7
- Docker version: 3.1.0

**Comment by jasonmccallister** [comment] 2021-03-01 12:11
@toddpadwick the issue with the versions not matching will be resolved in the next release and it is not related to this issue. I'm still perplexed by your other issue #249 and the complete paths versus the relative paths (I have been unable to reproduce on multiple machines).

I found a bug when creating nginx sites that _might_ resolve the issue and included a build with a few bug fixes for you to try.

However, can you use the Docker Desktop and manually remove your proxy and site containers (the little trashcan) and (using the build attach) run `nitro start` and `nitro apply`?

[nitro_darwin_x84_64.tar.gz](https://github.com/craftcms/nitro/files/6061473/nitro_darwin_x84_64.tar.gz)

To replace your current version, run `which nitro` and use `mv` to replace current binary with the downloaded (the versions match so if the `mv` command is successful you are good)

**Comment by toddpadwick** [comment] 2021-03-02 08:08
Hi @jasonmccallister  seems to work now after replacing that nitro file :)
Thanks a lot!

**Comment by jasonmccallister** [comment] 2021-03-02 19:01
This has been released in the latest beta!

**Closed by jasonmccallister** 2021-03-02 19:01 UTC
Labels: bug
