### ISSUE TITLE
`nitro db import` should work on compressed DB backups

### ISSUE THREAD

**Issue by benface** [craftcms/nitro#211] opened 2020-09-16 16:18 UTC
### Description

Importing a compressed DB backup (`.sql.zip`) as generated by Craft results in an error:
```
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR: ASCII '\0' appeared in the statement, but this is not allowed unless option --binary-mode is enabled and mysql is run in non-interactive mode. Set --binary-mode to 1 if ASCII '\0' is expected. Query: 'PK'.
read unix @->/run/docker.sock: read: connection reset by peer

Error: exit status 1
```

### Additional info

- Nitro version: 1.0.1
- Multipass version: 1.4.0+mac

**Comment by jasonmccallister** [comment] 2020-09-22 03:38
@benface this is a duplicate of #132. Closing out in favor of that ticket.

**Closed by jasonmccallister** 2020-09-22 03:38 UTC
Labels: bug
