### ISSUE TITLE
Rebooting PC causes Nitro sites to become inaccessible

### ISSUE THREAD

**Issue by DouglasKGlover** [craftcms/nitro#180] opened 2020-06-30 03:35 UTC
I may be missing something, but I have been trying to get Nitro up and running for local dev. Every time I get it going it's smooth and works fine, ignoring a few issues that I was able to find solutions for online relatively quickly. But when I restart or shutdown my computer and then later come back to continue working on it, the sites become inaccessible, with a generic "This site can't be reached" message from the browser.

Looking at "Nitro info" it looks like the IP has changed so I've tried updating that on my Craft CMS config files and local hosts file (Windows machine), but to no avail.

Any help at all would be greatly appreciated as this has been pretty solid to work with... until I reboot my computer.

**Comment by jasonmccallister** [comment] 2020-06-30 19:45
@DouglasKGlover you need to disable internet sharing, this seems to be a known thing with the way multipass using the Windows hypervisor. 

There is a tutorial on troubleshooting the windows networking here: https://multipass.run/docs/troubleshooting-networking-on-windows

I need to confirm, but it appears to resolve itself if you disable internet sharing on Windows.

**Comment by DouglasKGlover** [comment] 2020-06-30 20:19
@jasonmccallister I've done all of the steps provided on the tutorial you shared, as well as manually disabled Internet Sharing via Services and set it to disabled on startup. Unfortunately I am still unable to access my site for local dev. :(

**Comment by jasonmccallister** [comment] 2020-07-01 15:52
@DouglasKGlover did you reboot the host machine to apply those changes?

**Comment by DouglasKGlover** [comment] 2020-07-01 16:03
I did, yes. I'll note that the following from a user (goraxan) on Discord worked for me:

**@Doug same here (in Windows). IP changes every time I reboot. So what I do is: nitro stop; nitro start; nitro info (change .env database DSN with the new IP); nitro apply (this changes the hosts file with the new IP)**

Is there any way to prevent the machine from acquiring a new IP on Windows reboot? Not sure if this would be a Nitro or a Multipass thing, but seems directly tied to the Nitro machine itself as far as I can tell.

**Comment by jasonmccallister** [comment] 2020-07-02 17:58
@DouglasKGlover there is a hidden command called `nitro hosts` that will read the IP address of the machine and clean the hosts file. It will not touch the hosts.iscl file though.

This issue is somewhat related to multipass but the real issue is the network manager on windows hypervisors. I worked through this with someone else on windows, I will check if they are still having the issue after disabling internet sharing.

**Comment by delixyr** [comment] 2020-07-15 21:30
@jasonmccallister The issue still persists. Guess the issue is with Windows hyper-v default switch.

**Comment by jasonmccallister** [comment] 2020-12-14 19:05
@delixyr this is a Windows related issue and the next release will resolve this.

**Comment by jasonmccallister** [comment] 2021-02-05 19:31
@delixyr by next release, I really mean't v2 where we replaced Multipass with Docker. Here are the instructions for upgrading, Windows 10 is still a WIP... but mostly for WSL2 and Docker setup.. https://craftcms.com/docs/nitro/2.x/

**Comment by jasonmccallister** [comment] 2021-03-02 19:05
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).

**Closed by jasonmccallister** 2021-03-02 19:05 UTC
