### ISSUE TITLE
/app/config isn't writable by PHP. Please fix that. 

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/nitro#245] opened 2021-02-09 21:58 UTC
### Description

Installed Nitro2beta3 on Manjaro ARM for Raspberry Pi4; ran `nitro create test` - all seems to work, but navigating to http://test.nitro I'm met with a browser error saying

`/app/config isn't writable by PHP. Please fix that.`

```
[matt@pi4 ~]$ mkdir nitro/test
[matt@pi4 ~]$ cd nitro/test
[matt@pi4 test]$ nitro create test
Downloading https://github.com/craftcms/craft/archive/HEAD.zip ...
  … setting up project ✓
New site downloaded 🤓
Enter the hostname [test.nitro]: 
  ✓ setting hostname to test.nitro
  ✓ adding site ~/nitro/test/test
Enter the webroot for the site [web]: 
  ✓ using webroot web
Choose a PHP version: 
  1. 8.0
  2. 7.4
  3. 7.3
  4. 7.2
  5. 7.1
  6. 7.0
Enter your selection: 2
  ✓ setting PHP version 7.4
Add a database for the site [Y/n] y
Enter the new database name: test
  … creating database test ✓
Database added 💪
Should we update the env file? [Y/n] y
.env updated!
  … checking /home/matt/nitro/test/test/composer.json ✓
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 87 installs, 0 updates, 0 removals
... [REMOVED FOR BREVITY] ...
Generating optimized autoload files
49 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
composer install completed 🤘
Apply changes now [Y/n] y
Checking network…
  ✓ network ready
Checking proxy…
  ✓ proxy ready
Checking databases…
  … checking mariadb-10.5-3306.database.nitro ✓
Checking services…
  … checking dynamodb service ✓
  … checking mailhog service ✓
  … checking redis service ✓
Checking sites…
  … checking test.nitro ✓
Checking proxy…
  … updating proxy ✓
Updating hosts file (you might be prompted for your password)
[sudo] password for matt: 
Adding sites to hosts file…
  … modifying hosts file ✓
```

### Additional info

- Nitro version: 2beta3
- OS: Manjaro ARM; Raspberry Pi 4

... I may be going nuts, but `app/config` does not seem like a normal Craft path?

```
[matt@pi4 test]$ nitro context
Craft Nitro 2.0.0-beta.3

Configuration:	 /home/matt/.nitro/nitro.yaml

Sites:
  hostname:	 test.nitro
  php:	 7.4
  webroot:	 web
  path:	 ~/nitro/test/test
  ---
Databases:
  engine:	 mariadb 10.5 	hostname: mariadb-10.5-3306.database.nitro
  username:	 nitro 	password: nitro
  port:	 3306
  ---
[matt@pi4 test]$
```

**Comment by jasonmccallister** [comment] 2021-02-09 22:07
@MattWilcox this is a duplicate of #240. Not sure we are going to force permission settings on install for better cross-platform support. Going to close this out in favor of the other ticket who is also a Linux OS user :).

**Closed by jasonmccallister** 2021-02-09 22:07 UTC
Labels: bug

**Comment by jasonmccallister** [comment] 2021-02-09 22:09
@MattWilcox to adress this:

> may be going nuts, but app/config does not seem like a normal Craft path

When a site is added to the container, its mounted path is `/app/<files>` so the error outputs the complete path inside of the container.
