### ISSUE TITLE
The `add` command adds a mount without confirming or checking for existing mounts

### ISSUE THREAD

**Issue by lukeholder** [craftcms/nitro#86] opened 2020-04-23 14:18 UTC
Adding a site creates a mount automatically at the moment without checking if it is redundant.

Let's say I have this already:

```yaml
mounts:
 - source: /Volumes/Dev
 - dest: /nitro/dev
```

I think this should be possible:

```
$ cd /Volumes/Dev/craft3.test
$ nitro add
/Volumes/Dev is already mounted at /nitro/dev. Using that instead of creating a new mount.
→ What should the hostname be? [craft3.test] $
(etc...)
```
So the add command will still add the new sites entry & apply it for me, etc.
Just without creating a redundant mount

**Comment by jasonmccallister** [comment] 2020-04-29 18:56
Thanks @lukeholder! I just addressed this and it will be tagged in the next release!

**Comment by brandonkelly** [comment] 2020-05-05 11:32
@jasonmccallister I don’t think this is resolved yet. I just tried running `add` on 0.11.4 within a directory a couple levels below an already-mounted directory, and Nitro tried to create the mount:

```
$ cd /Volumes/Sites/support/craft3.support.test
$ nitro add
What should the hostname be?
Enter a value (Default is craft3.support.test): 

Where is the webroot?
Enter a value (Default is web): 

craft3.support.test has been added to config file.
Apply changes from config now?
Enter a value (Default is y): 

mount failed: The following errors occurred:                                    
"nitro-dev:/nitro/sites/craft3.support.test" is already mounted
Error: exit status 2                                             
```

**Comment by jasonmccallister** [comment] 2020-05-08 12:17
I have the following config file:

```
$ nitro context
Using config: /Users/jasonmccallister/.nitro/nitro-dev.yaml
------
php: "7.4"
mounts:
  - source: ~/dev/craft-dev
    dest: /nitro/sites/nitro-demo.test
  - source: ~/go/src/github.com/craftcms/nitro/demo-site
    dest: /nitro/sites/demo-site
databases:
  - engine: postgres
    version: "12"
    port: "5432"
sites:
  - hostname: nitro-demo.test
    webroot: /nitro/sites/nitro-demo.test/web
  - hostname: demo-site
    webroot: /nitro/sites/demo-site/web
```

Running this shows me an error and there is nothing else to to:

```
$ nitro add demo-site
What should the hostname be? [demo-site] 
Where is the webroot? [web] 
/Users/jasonmccallister/go/src/github.com/craftcms/nitro/demo-site is already mounted at /nitro/sites/demo-site . Using that instead of creating a new mount.
demo-site has already been set.
There are no changes to apply, skipping...
```

I'm going to run your example to see if I can reproduce.

**Comment by brandonkelly** [comment] 2020-05-12 00:44
Looks like in that example you are adding the exact site that is already mounted. What happens if you try to add a site that is buried a few levels deep within `~/dev/craft-dev/` though?

**Comment by jasonmccallister** [comment] 2020-06-01 21:29
Beta 8 should handle this, can you confirm and we can close this out?

**Closed** 2020-06-02 19:37 UTC
Labels: bug

**Comment by jamiewade** [comment] 2020-06-11 12:29
@jasonmccallister I'm getting the `"nitro-dev:/home/ubuntu/sites" is already mounted` error locally.

I'm running Windows 10, and I have a dedicated SSD for my local sites (`S:`), so I have mounted the entire directory:

```
mounts:
  - source: S:/
    dest: /home/ubuntu/sites
```

I have two sites in my config file at the moment, and those are working. To add a third site, I'm just adding:

```
- hostname: xxx.nitro
  webroot: /home/ubuntu/sites/xxx/public
```

Then running

`nitro apply`

Which returns:

```
$ nitro apply
Mounting S:/ to nitro-dev
Adding site xxx.nitro to nitro-dev
mount failed: The following errors occurred:
"nitro-dev:/home/ubuntu/sites" is already mounted
Error: exit status 2
```
