### ISSUE TITLE
Docker - Error: invalid mount config for type "bind": bind source path does not exist on a Mac

### ISSUE THREAD

**Issue by toddpadwick** [craftcms/nitro#249] opened 2021-02-22 11:49 UTC
### Description
1. I have upgraded Nitro from 1 to 2 following the instructions in the docs. 
I have installed docker, 
2. added docker to the list of applications which allowed full disc access in Mac system preferences. 
3. I have also ensured the directory exists and is added to the list of shared files in docker settings.

I have explored multiple threads which reference this error – [one of which](https://github.com/docker/docker.github.io/issues/4709) says the most common issue is docker not having access to that directory either by not being added to the mac system preferences privacy list (which I did above), or not in the shared file list in docker preferences (also something I had already done).

So I'm now wondering if this is a nitro problem?

### Steps to reproduce

1. Install nitro and docker
2. run nitro add when in the directory of my project
3. run nitro apply 

### full error response
```
  nitro apply
  Checking network…
    ✓ network ready
  Checking proxy…
    ✓ proxy ready
  Checking databases…
    … checking mysql-8.0-3306.database.nitro ✓
    … checking postgres-13-5432.database.nitro ✓
  Checking services…
    … checking dynamodb service ✓
    … checking mailhog service ✓
    … checking redis service ✓
  Checking sites…
    … checking madefair-api ✗
  Error: unable to create the container, Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /users/toddpadwick/sites/madefair-api

```

### Additional info

- Nitro version: `2.0.0-beta.5`
- Docker version: `3.1.0`

**Comment by jasonmccallister** [comment] 2021-02-22 13:16
Hi @toddpadwick, that sounds like it might be a Docker setting that is causing the issue. 

Can you open your **Docker Preferences** > **Resources** > **File Sharing** and verify that the path you are trying to add is included in the list? Also, can you provide the path to the site from your config file?

Here is a screenshot of mine file sharing settings for reference:

![CleanShot 2021-02-22 at 08 10 14@2x](https://user-images.githubusercontent.com/5354908/108713209-e5670980-74e5-11eb-9277-b229a7046351.png)

**Comment by toddpadwick** [comment] 2021-02-22 13:20
Hi @jasonmccallister 

Here is my docker file sharing settings:

<img width="594" alt="Screenshot 2021-02-22 at 14 17 52" src="https://user-images.githubusercontent.com/36191462/108713795-0432c380-7519-11eb-9e89-ba2941ff501b.png">

and the site Nitro config is
```
      hostname: madefair-api
      path: /users/toddpadwick/sites/madefair-api
      version: "8.0"
      webroot: web
      xdebug: false
      blackfire: false
```

**Comment by jasonmccallister** [comment] 2021-02-22 13:35
It looks like the preferences has `Sites` and the path added `sites`. Assuming Nitro grabbed the right path, try changing it in the Docker preferences and apply those changes.

**Comment by toddpadwick** [comment] 2021-02-22 13:48
No, I was in the directory and simply ran `nitro add`, and followed the steps. So does it mean I installed Nitro in the wrong place if it's not creating a relative path from my user directory? should I have installed or initiated it on my user directory instead of the root - I assumed it was a global installation.

The shared directory preference panel opens a file browser window, so no way to manually enter a path that I can see.

**Comment by jasonmccallister** [comment] 2021-02-22 14:29
It should still work but I think the issue is the case sensitive path in the Docker settings.  

As far as adding the path, it's hidden but you can click into this field to add it and will probably need to remove the existing one that does not have the correct capitalization.

![CleanShot 2021-02-22 at 09 25 18](https://user-images.githubusercontent.com/5354908/108721526-14827880-74f0-11eb-88d7-12165068e244.png)

**Comment by toddpadwick** [comment] 2021-02-22 14:54
You were corret, it was due to capitalisation. However, _not with docker_, but with Nitro: 
I tried making the path in docker lowercase but that didn't work as the directory is in fact, capitalised. So instead, I manually overrode the auto-generated host path and changed `/users/toddpadwick/sites` to `/Users/toddpadwick/Sites`

So there may be a bug there whereby it flattens all paths to lowercase when they are created automatically?

**Comment by jasonmccallister** [comment] 2021-02-22 15:29
We don't flatten any paths, we use the go standard library to get the path names which is pretty well tested. Can you list the contents of your directory in terminal, and see if maybe the site is correct in the terminal output? 

`ls -la` on your home directory?￼

**Comment by toddpadwick** [comment] 2021-02-22 15:50
```
drwxr-xr-x+  51 toddpadwick  staff      1632 22 Feb 16:15 .
drwxr-xr-x    5 root         admin       160  5 Dec  2019 ..
-rw-------    1 toddpadwick  staff         3 16 Mar  2020 .CFUserTextEncoding
-rw-r--r--@   1 toddpadwick  staff     12292 22 Feb 16:25 .DS_Store
drwxr-xr-x    2 toddpadwick  staff        64 30 Mar  2020 .FontForge
drwx------  296 toddpadwick  staff      9472 22 Feb 11:47 .Trash
-rw-------    1 toddpadwick  staff     10418 22 Feb 11:55 .bash_history
-rw-r--r--@   1 toddpadwick  staff       766  2 Oct 12:54 .bash_profile
-rw-r--r--@   1 toddpadwick  staff       263 27 Sep  2019 .bash_profile.backup
drwx------   47 toddpadwick  staff      1504 22 Feb 11:56 .bash_sessions
-rw-r--r--@   1 toddpadwick  staff       368  2 Oct 13:02 .bashrc
drwxr-xr-x    3 toddpadwick  staff        96 27 Nov 21:48 .cisco
drwxr-xr-x    6 toddpadwick  staff       192 17 Mar  2020 .composer
drwx------    4 toddpadwick  staff       128 30 Jul  2020 .config
drwx------    3 toddpadwick  staff        96 25 Aug 20:11 .cups
drwxr-xr-x    8 toddpadwick  staff       256 22 Feb 15:44 .docker
-rw-r--r--    1 toddpadwick  staff       128 20 Mar  2020 .docker-sync-global.yml
drwxr-xr-x   14 toddpadwick  staff       448 19 Dec 21:55 .dropbox
drwxr-xr-x    4 toddpadwick  staff       128 20 Mar  2020 .gem
-rw-r--r--    1 toddpadwick  staff        64 20 Mar  2020 .gitconfig
drwxrwxrwx   27 toddpadwick  staff       864 12 Feb 16:56 .goodsync
-rw-------    1 toddpadwick  staff       251  4 Nov 12:33 .mysql_history
drwxr-xr-x    5 toddpadwick  staff       160 22 Feb 16:22 .nitro
drwxr-xr-x    3 toddpadwick  staff        96  7 Jul  2020 .node-gyp
drwxr-xr-x   10 toddpadwick  staff       320  8 Feb 15:57 .npm
-rw-r--r--    1 toddpadwick  staff        74  2 Jan 17:46 .nuxtrc
drwxr-xr-x   27 toddpadwick  staff       864 17 Mar  2020 .nvm
-rw-r--r--@   1 toddpadwick  staff       244 17 Jun  2020 .profile
drwxr-xr-x    3 toddpadwick  staff        96 16 Mar  2020 .qd
drwxr-xr-x    7 toddpadwick  staff       224 17 Oct  2019 .ssh
-rw-------    1 toddpadwick  staff      9598 22 Feb 16:15 .viminfo
drwxr-xr-x    4 toddpadwick  staff       128 29 Dec 17:40 .vue-cli-ui
drwxr-xr-x    4 toddpadwick  staff       128 22 Mar  2020 .vue-templates
-rw-r--r--    1 toddpadwick  staff        32 18 Jun  2020 .vuerc
-rw-r--r--    1 toddpadwick  staff     46568 17 Mar  2020 .zcompdump
-rw-------    1 toddpadwick  staff       840 17 Mar  2020 .zsh_history
drwx------@   5 toddpadwick  staff       160 17 Mar  2020 Applications
drwx------@   4 toddpadwick  staff       128 22 Feb 11:57 Creative Cloud Files
drwx------@  39 toddpadwick  staff      1248 22 Feb 16:34 Desktop
drwx------+   8 toddpadwick  staff       256 24 Dec 08:49 Documents
drwx------@  33 toddpadwick  staff      1056 22 Feb 15:33 Downloads
drwx------@   6 toddpadwick  staff       192 19 Dec 22:00 Dropbox
lrwx------    1 toddpadwick  staff        20 22 Feb 11:57 Google Drive -> /Volumes/GoogleDrive
drwx------+  72 toddpadwick  staff      2304 29 Jan 11:59 Library
drwx------+  15 toddpadwick  staff       480 28 Jan 17:32 Movies
drwx------+  10 toddpadwick  staff       320 30 Dec 15:52 Music
drwx------+  66 toddpadwick  staff      2112  1 Jun  2020 Pictures
drwxr-xr-x+   5 toddpadwick  staff       160 17 Mar  2020 Public
drwxr-xr-x   54 toddpadwick  staff      1728  5 Feb 15:03 Sites
```

I can confirm Users is also capitalised.

**Comment by jasonmccallister** [comment] 2021-02-22 18:07
Hmmm ok, when you ran `nitro add` did `cd` into the `~/Sites/` directory and use `nitro add <site-name>` or `cd` into `~/Sites/site-name` and run `nitro add`?

You also do not have any special attributes on the Sites directory (indicated by the trailing `@` symbol).

**Comment by toddpadwick** [comment] 2021-02-22 18:33
I `cd`'d into an already existing project directory (`madefair-api`), and then I ran `nitro add`. 

No, i don't think I have any special attributes on the directory. But not sure exactly what you mean by this?

I also tried re-adding the project again just now and I can confirm it flattened the case again to `/users/toddpadwick/sites/madefair-api` rather than `/Users/toddpadwick/Sites/madefair-api`

**Comment by jasonmccallister** [comment] 2021-02-22 20:00
In your root directory, can you make two new directories and see if they show up using the `ls` command? I'm following instructions [from this post](https://apple.stackexchange.com/a/90425/85315).

e.g.:

```bash
mkdir dev
mkdir Dev
ls de*
```

I'm not sure how to check case sensitive drives in macOS anymore, they are making it harder :)

**Comment by toddpadwick** [comment] 2021-03-01 08:13
Okay, so it seems that although the paths are case sensitive, you cannot add two directories one lower and one upper. I tried to add both but it said `File Exists`. I don't know if that's helpful?

**Comment by jasonmccallister** [comment] 2021-03-02 19:11
Can you go into your sites directory and run `pwd` and provide the output?

**Comment by jasonmccallister** [comment] 2021-08-05 21:17
@toddpadwick is this still an issue for you? We have been unable to reproduce it and there have been no other reports.

**Comment by jasonmccallister** [comment] 2022-07-06 15:28
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.

**Closed by jasonmccallister** 2022-07-06 15:28 UTC
Labels: question
