### ISSUE TITLE
Issue with file ownership (user 1000)

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/nitro#181] opened 2020-07-01 10:56 UTC
Hi there,

I do have some strange issue with the latest beta (10).

Ownership of my project files in the vm is ubuntu:ubuntu (ubuntu is user 1000) which seems ok.
Ownership of my project files in my local folder is my-user:staff for some files, and 1000:1000 for many others, as if it wanted them to be the user ubuntu which doesn't exists locally on my machine.

If I edit a file in the vm, it changes the ownership locally to 1000:1000 each and every time.

Attached is a local and remote ls of a default craft install.

<img width="537" alt="Capture d’écran 2020-07-01 à 12 54 13" src="https://user-images.githubusercontent.com/14908712/86236271-1c289200-bb9a-11ea-8cab-39b94632e24d.png">

<img width="481" alt="Capture d’écran 2020-07-01 à 12 55 34" src="https://user-images.githubusercontent.com/14908712/86236316-2cd90800-bb9a-11ea-85ce-321950b18902.png">

**Comment by jasonmccallister** [comment] 2020-07-01 15:53
@JeanLucEsser which version of nitro are you using?

**Comment by JeanLucEsser** [comment] 2020-07-01 15:55
I'm using nitro beta 10 which is the latest I believe.

**Comment by jasonmccallister** [comment] 2020-07-01 16:57
@JeanLucEsser lets try the following, can you perform the following steps?

1. Stop the machine using `nitro stop`
2. Change directories to the one above the affected sites: `cd <dir/above/uc-senat-project>`
3. Force the user and group on the files using `sudo chown -R <username>:<group> <uc-senate>`
4. Run `nitro start`
5. Edit the files in the vm using `nitro ssh`
6. Verify the files permissions have not changed

**Comment by JeanLucEsser** [comment] 2020-07-02 08:41
@jasonmccallister yes it did resolve the issue.

I did the exact same thing previously without first stopping nitro and it didn't work.
I'll keep you posted if the permissions change again.

Have you been able to reproduce the issue on a fresh install?
1. Start machine
2. Create project directory on local
3. Run `nitro add` from project directory
4. SSH into machine
5. Composer install Craft to project directory
6. Verify permissions in local project directory

**Comment by jasonmccallister** [comment] 2020-07-02 17:56
I was able to reproduce it in an earlier beta when running `nitro refresh`. I can't reproduce it from a new machine on beta-10 that I created yesterday.

**Comment by jasonmccallister** [comment] 2020-07-22 23:11
@JeanLucEsser is this still an issue for you?

**Comment by JeanLucEsser** [comment] 2020-07-23 08:24
Unfortunately it is. I didn't follow suit because it looks like you cannot reproduce it from a new machine so maybe it is something with my setup, I'll try to find some time to fully start from scratch to see how it goes.

Something I can tell you is that forcing the user and group on the files almost did the trick. I still get the package.* files reverting to the wrong permission every time I make an `npm install` from the machine. For the record npm has been installed on the new machine via n-install (`curl -L https://git.io/n-install | bash`).

What do you think we should do in the meantime? It looks I'm the only one with this issue.

**Comment by jasonmccallister** [comment] 2021-03-02 19:05
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).

**Closed by jasonmccallister** 2021-03-02 19:05 UTC
Labels: question
