### ISSUE TITLE
Can't update Craft from Nitro

### ISSUE THREAD

**Issue by umkasanki** [craftcms/nitro#401] opened 2021-08-29 15:40 UTC
### Description
I am getting an error when trying to update Craft from Nitro:

```
/app $ ./craft update
Fetching available updates ... Exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 6: Could not resolve host: api.craftcms.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.craftcms.com/v1/updates'
in /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
```

How can I fix this error? 

### Steps to reproduce

1. Open site container via `nitro ssh`
2. Run `./craft update`

### Additional info

- Nitro version: 2.0.8
- Docker version: 3.5.2
- Windows 10 / WSL2

**Comment by jasonmccallister** [comment] 2021-08-30 14:04
@umkasanki can you run `nitro ssh` and run `curl --verbose https://api.craftcms.com/v1/updates`? If that fails can you try the same `curl` command on your host machine?

**Comment by umkasanki** [comment] 2021-08-30 15:49
> 
> 
> @umkasanki can you run `nitro ssh` and run `curl --verbose https://api.craftcms.com/v1/updates`? If that fails can you try the same `curl` command on your host machine?

```
mishkin@DESKTOP-ELHJ3EU:/mnt/c/Users/oleg$ nitro ssh
Select a site:
  1. bkbn.nitro
  2. craft.nitro
  3. starter-blog.nitro
  4. test.nitro
Enter your selection: 1
/app $ curl --verbose https://api.craftcms.com/v1/updates
* Could not resolve host: api.craftcms.com
* Closing connection 0
curl: (6) Could not resolve host: api.craftcms.com
/app $ exit
Error: exit status 6
mishkin@DESKTOP-ELHJ3EU:/mnt/c/Users/oleg$ curl --verbose https://api.craftcms.com/v1/updates
*   Trying 52.34.209.81:443...
* TCP_NODELAY set
* Connected to api.craftcms.com (52.34.209.81) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.craftcms.com
*  start date: May 30 00:00:00 2021 GMT
*  expire date: Jun 28 23:59:59 2022 GMT
*  subjectAltName: host "api.craftcms.com" matched cert's "*.craftcms.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /v1/updates HTTP/1.1
> Host: api.craftcms.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: x-craft-allow-trials, x-craft-license, x-craft-license-domain, x-craft-license-edition, x-craft-license-status, x-craft-plugin-license-editions, x-craft-plugin-license-statuses, x-craft-plugin-licenses
< Content-Type: application/json; charset=UTF-8
< Date: Mon, 30 Aug 2021 15:48:23 GMT
< Permissions-Policy: interest-cohort=()
< Server: Apache
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 60
< Connection: keep-alive
<
* Connection #0 to host api.craftcms.com left intact
mishkin@DESKTOP-ELHJ3EU:/mnt/c/Users/oleg$
```

**Comment by jasonmccallister** [comment] 2021-08-30 16:04
Do you have a VPN? You are running this in WSL2/bash terminal correct?

**Comment by umkasanki** [comment] 2021-08-30 16:48
No, I have no VPN.
I use nativ Windows/WSL teminal
![изображение](https://user-images.githubusercontent.com/496132/131374992-037423b8-533c-4bb0-bc2b-ad078339b793.png)

**Comment by jasonmccallister** [comment] 2021-08-30 17:32
Is there a proxy setting on Docker Desktop or are you on a work network?

**Comment by angrybrad** [comment] 2021-08-30 18:01
Maybe Windows Defender/Firewall related?

**Comment by umkasanki** [comment] 2021-08-31 06:44
@jasonmccallister @angrybrad  Thanks for fast reply.
Private network.
Defender/Firewall disabled.
My Docker settings:

![изображение](https://user-images.githubusercontent.com/496132/131454022-79f606d6-beac-430f-a14f-31dbf6e54d0e.png)
![изображение](https://user-images.githubusercontent.com/496132/131454065-8a50f83c-8664-42fb-b600-ae2edda2ab92.png)

The problem is still present
![изображение](https://user-images.githubusercontent.com/496132/131454700-84d300f5-5404-432b-bf51-61f3109cbc8c.png)

**Comment by jasonmccallister** [comment] 2021-09-01 02:57
Can you try the following, without using Nitro lets check network connectvity in a normal container. Can you try the following?

```shell
docker run --rm -it debian bash
apt update && apt install -y curl
curl --verbose https://api.craftcms.com/v1/updates
```

If that does not have connectivity its an issue with the WSL2 installation. There are a couple of related issues on the WSL2 board: https://github.com/MicrosoftDocs/WSL/issues/422.

**Comment by umkasanki** [comment] 2021-09-01 08:19
@jasonmccallister Done
```
mishkin@DESKTOP-ELHJ3EU:/mnt/c/Users/oleg$ docker run --rm -it debian bash
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
4c25b3090c26: Pull complete
Digest: sha256:38988bd08d1a5534ae90bea146e199e2b7a8fca334e9a7afe5297a7c919e96ea
Status: Downloaded newer image for debian:latest
root@22d93868b975:/# apt update && apt install -y curl
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Preparing to unpack .../12-libldap-common_2.4.57+dfsg-3_all.deb ...
Unpacking libldap-common (2.4.57+dfsg-3) ...
Selecting previously unselected package libsasl2-modules:amd64.
Preparing to unpack .../13-libsasl2-modules_2.1.27+dfsg-2.1_amd64.deb ...
Unpacking libsasl2-modules:amd64 (2.1.27+dfsg-2.1) ...
Selecting previously unselected package publicsuffix.
Preparing to unpack .../14-publicsuffix_20210108.1309-1_all.deb ...
Unpacking publicsuffix (20210108.1309-1) ...
Setting up libpsl5:amd64 (0.21.0-1.2) ...
Setting up libbrotli1:amd64 (1.0.9-2+b2) ...
Setting up libsasl2-modules:amd64 (2.1.27+dfsg-2.1) ...
Setting up libnghttp2-14:amd64 (1.43.0-1) ...
Setting up libldap-common (2.4.57+dfsg-3) ...
Setting up libsasl2-modules-db:amd64 (2.1.27+dfsg-2.1) ...
Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-2+b2) ...
Setting up libsasl2-2:amd64 (2.1.27+dfsg-2.1) ...
Setting up libssh2-1:amd64 (1.9.0-2) ...
Setting up openssl (1.1.1k-1+deb11u1) ...
Setting up publicsuffix (20210108.1309-1) ...
Setting up libldap-2.4-2:amd64 (2.4.57+dfsg-3) ...
Setting up ca-certificates (20210119) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Updating certificates in /etc/ssl/certs...
129 added, 0 removed; done.
Setting up libcurl4:amd64 (7.74.0-1.3+b1) ...
Setting up curl (7.74.0-1.3+b1) ...
Processing triggers for libc-bin (2.31-13) ...
Processing triggers for ca-certificates (20210119) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
root@22d93868b975:/# curl --verbose https://api.craftcms.com/v1/updates
*   Trying 44.238.34.105:443...
* Connected to api.craftcms.com (44.238.34.105) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.craftcms.com
*  start date: May 30 00:00:00 2021 GMT
*  expire date: Jun 28 23:59:59 2022 GMT
*  subjectAltName: host "api.craftcms.com" matched cert's "*.craftcms.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /v1/updates HTTP/1.1
> Host: api.craftcms.com
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: x-craft-allow-trials, x-craft-license, x-craft-license-domain, x-craft-license-edition, x-craft-license-status, x-craft-plugin-license-editions, x-craft-plugin-license-statuses, x-craft-plugin-licenses
< Content-Type: application/json; charset=UTF-8
< Date: Wed, 01 Sep 2021 08:18:13 GMT
< Permissions-Policy: interest-cohort=()
< Server: Apache
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 60
< Connection: keep-alive
<
* Connection #0 to host api.craftcms.com left intact
{"message":"Unable to determine the current Craft version."}root@22d93868b975:/#

**Comment by umkasanki** [comment] 2021-09-07 13:29
I've tried to change host file manually

```
//login with docker
sudo docker exec -it bkbn.nitro sh

// open host file 
vi /etc/hosts

// add your local url 
52.34.209.81  api.crafcms.com
```

But host file is not writable
![изображение](https://user-images.githubusercontent.com/496132/132353037-284cd9f7-112a-4952-bf74-8f00809352d7.png)

**Comment by umkasanki** [comment] 2021-09-10 05:38
Any other ideas how to fix this?
How to add an entry to the host file correctly? Am I doing it wrong?
Thanks

**Comment by jasonmccallister** [comment] 2021-09-10 13:50
@umkasanki you should never need to modify the `/etc/hosts` file in the container. 

I did some quick research and found quite a new people having similar issues on Docker Desktop for Windows. I'm not sure what the root cause is for the networking issue but some people mentioned that performing an uninstall and reinstall of Docker Desktop did the trick, but I'm not sure that is the best answer.

Can you run the following?

```
docker run --rm -it --network=nitro-network debian bash
apt update && apt install -y curl
curl --verbose https://api.craftcms.com/v1/updates
```

This will create the same container inside of the network that Nitro created for the containers. Also can you provide the output of `docker network inspect nitro-network`?

**Comment by umkasanki** [comment] 2021-09-10 14:07
@jasonmccallister Done
```
mishkin@DESKTOP-ELHJ3EU:/mnt/c/Users/oleg$ docker run --rm -it --network=nitro-network debian bash
root@52a13dd5f935:/# apt update && apt install -y curl
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [113 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [36.8 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [31.1 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8178 kB]
Fetched 8402 kB in 2s (4301 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-2+b2) ...
Setting up libsasl2-2:amd64 (2.1.27+dfsg-2.1) ...
Setting up libssh2-1:amd64 (1.9.0-2) ...
Setting up openssl (1.1.1k-1+deb11u1) ...
Setting up publicsuffix (20210108.1309-1) ...
Setting up libldap-2.4-2:amd64 (2.4.57+dfsg-3) ...
Setting up ca-certificates (20210119) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Updating certificates in /etc/ssl/certs...
129 added, 0 removed; done.
Setting up libcurl4:amd64 (7.74.0-1.3+b1) ...
Setting up curl (7.74.0-1.3+b1) ...
Processing triggers for libc-bin (2.31-13) ...
Processing triggers for ca-certificates (20210119) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
root@52a13dd5f935:/# curl --verbose https://api.craftcms.com/v1/updates
*   Trying 44.238.34.105:443...
* Connected to api.craftcms.com (44.238.34.105) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.craftcms.com
*  start date: May 30 00:00:00 2021 GMT
*  expire date: Jun 28 23:59:59 2022 GMT
*  subjectAltName: host "api.craftcms.com" matched cert's "*.craftcms.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /v1/updates HTTP/1.1
> Host: api.craftcms.com
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: x-craft-allow-trials, x-craft-license, x-craft-license-domain, x-craft-license-edition, x-craft-license-status, x-craft-plugin-license-editions, x-craft-plugin-license-statuses, x-craft-plugin-licenses
< Content-Type: application/json; charset=UTF-8
< Date: Fri, 10 Sep 2021 14:06:14 GMT
< Permissions-Policy: interest-cohort=()
< Server: Apache
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 60
< Connection: keep-alive
<
* Connection #0 to host api.craftcms.com left intact
{"message":"Unable to determine the current Craft version."}root@52a13dd5f935:/#

**Comment by jasonmccallister** [comment] 2021-09-10 19:45
Can you also provide the output of `docker network inspect nitro-network`?

**Comment by umkasanki** [comment] 2021-09-11 05:43
```
mishkin@DESKTOP-ELHJ3EU:/mnt/c/Users/oleg$ docker network inspect nitro-network
[
    {
        "Name": "nitro-network",
        "Id": "e3ea776a2cc614bcd55970805d91ef5240dfdb3ac3392b93558cb271b61930c7",
        "Created": "2021-03-14T05:44:30.483338Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "105e9612cedbabe0b3912d621d14dd0423b7d5ebc80fb958d78f2d472ee0a427": {
                "Name": "postgres-11-5433.database.nitro",
                "EndpointID": "83cd81bc9ce8ac9b8438220e3b271ba26eb1235dfdace2356f68b84cd3ec9c09",
                "MacAddress": "02:42:ac:12:00:08",
                "IPv4Address": "172.18.0.8/16",
                "IPv6Address": ""
            },
            "17f0421fb70185ea327fc109b13145ce4595e4881cbc416b4f3b69b1dc04f91e": {
                "Name": "kvdl.nitro",
                "EndpointID": "641db9f46dd10ce7abc1579a070a8e62a036002d951bc468d75135b516afe1f8",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "2b9e44f1bfde43de1176419f9719fd0bfd7c90a93498bbeac78d5342b50755f2": {
                "Name": "craft.nitro",
                "EndpointID": "5cc6be47043973163ca5bb005cbeeefe44169d9b24d70993ad3ded08922b405d",
                "MacAddress": "02:42:ac:12:00:0a",
                "IPv4Address": "172.18.0.10/16",
                "IPv6Address": ""
            },
            "52e254983d5dbf9aaef7a2e54cf67a13b302ff44aa4aa275c49c4107d951b47f": {
                "Name": "starter-blog.nitro",
                "EndpointID": "5d5a2746f7810b8ed537d4eb7049a7979be16712fa041fe87b05add5f7f33f16",
                "MacAddress": "02:42:ac:12:00:06",
                "IPv4Address": "172.18.0.6/16",
                "IPv6Address": ""
            },
            "5aa92c2e633d54e700b73ea2f950117a0211441dd974f99ce85c8cd502f32578": {
                "Name": "mysql-8.0-3306.database.nitro",
                "EndpointID": "df80f5e81431eeaa1c11a89c584cbf47397cc454d41e50a3b1be1eb2c6bb27b4",
                "MacAddress": "02:42:ac:12:00:0d",
                "IPv4Address": "172.18.0.13/16",
                "IPv6Address": ""
            },
            "62bb9145e13f81a6e308fff95f4d96992e32cd6298f8e11334293e0da2d459c7": {
                "Name": "postgres-13-5432.database.nitro",
                "EndpointID": "c542d401af0223935bc324955064eabb9c24b8392d8582bec1ad4a2a1e01a186",
                "MacAddress": "02:42:ac:12:00:0c",
                "IPv4Address": "172.18.0.12/16",
                "IPv6Address": ""
            },
            "8dcd16970c85c94c5ea746a64662446915fe84e5e967ab1a92415f4988a3c28c": {
                "Name": "test.nitro",
                "EndpointID": "702fb6a3b8de2addced18eb6887b3b80f1e557e0d66b02ff248b741dc3995f0c",
                "MacAddress": "02:42:ac:12:00:07",
                "IPv4Address": "172.18.0.7/16",
                "IPv6Address": ""
            },
            "aabd5ae4be92d4c970b9a2f092fba60afd4453fe37c9147cda9f52bae68ced7b": {
                "Name": "redis.service.nitro",
                "EndpointID": "1db9f7208a41898d6d657ef625f3bf8018160b3fdf0fa3f8b1080395a8ac1ba8",
                "MacAddress": "02:42:ac:12:00:0b",
                "IPv4Address": "172.18.0.11/16",
                "IPv6Address": ""
            },
            "b73ee6bffcbfe5d2b6ed61c619dc585d2986fedf95560fedd6927bf312431045": {
                "Name": "nitro-proxy",
                "EndpointID": "9c12eaaf0dbc8f00bdb7e41da9204a7bfe988576245af48a5c5cbf1dc8cc1b38",
                "MacAddress": "02:42:ac:12:00:0e",
                "IPv4Address": "172.18.0.14/16",
                "IPv6Address": ""
            },
            "d263d6a14d0bb98f4a8e80ecbf8cac0533a3002e6bf79e969a753bd05e3bd826": {
                "Name": "postgres-11.12-5434.database.nitro",
                "EndpointID": "75af494b4d48855204ddf50c01d63dc1014b7a63fcc3f0f588c7607e1851c1a6",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            },
            "ec7c7d6ee1ea151e9ef690c6718709dadb2b3a3f59e5258d4ce67641edd6d374": {
                "Name": "mysql-5.7-3307.database.nitro",
                "EndpointID": "45bac289bc7d23480adb88added3d37873ce739275482ac1f31906081575f364",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "ecf2e1781523f32b6b81b0cee833741fde4068a6d77792d8a1371a2a997d3470": {
                "Name": "bkbn.nitro",
                "EndpointID": "7bcce9ae73605c1be220b28cdf6b114a87ec5d2fd29739f214cbff0bfef7c01a",
                "MacAddress": "02:42:ac:12:00:09",
                "IPv4Address": "172.18.0.9/16",
                "IPv6Address": ""
            },
            "fb264163c70c86792e3971f24f8ebbdcbbe9746f1b955dd4ccaa774b8adb6a37": {
                "Name": "pgsql.nitro",
                "EndpointID": "9612c28dd1e943f365eeb2cfbb5c91f55c4e076730331b7c659cd492d2864636",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.craftcms.nitro": "true",
            "com.craftcms.nitro.network": "true"
        }
    }
]
mishkin@DESKTOP-ELHJ3EU:/mnt/c/Users/oleg$

**Comment by jasonmccallister** [comment] 2022-07-06 15:34
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.

**Closed by jasonmccallister** 2022-07-06 15:34 UTC
Labels: bug
